import { Patient, PHCCenter, DiseaseOutbreak, PrescriptionAnalysisResult } from '@/types';

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'PT-9021',
    name: 'Rameshwar Patil',
    age: 58,
    gender: 'Male',
    village: 'Kalyanpur, Ward 4',
    contact: '+91 98231 44102',
    symptoms: ['Acute crushing chest pain', 'Profuse diaphoresis', 'Radiation to left arm'],
    vitals: {
      bloodPressure: '168/104',
      heartRate: 118,
      spO2: 89,
      temperature: 98.4,
      respiratoryRate: 26,
    },
    severity: 'ESI-1',
    triageReason: 'High suspicion of Acute ST-Elevation Myocardial Infarction with hypoxemia. Immediate resuscitation & tertiary cardiology transfer required.',
    timestamp: '10 mins ago',
    assignedDoctor: 'Dr. Anita Deshmukh (PHC Lead)',
    status: 'In Consultation',
    recommendedActions: [
      'High-flow Oxygen via Mask at 6L/min',
      'Immediate 12-lead ECG capture',
      'Administer Aspirin 300mg + Clopidogrel 300mg loading dose',
      'Dispatch 108 Advanced Life Support (ALS) Ambulance to District Civil Hospital',
    ],
  },
  {
    id: 'PT-9022',
    name: 'Sunita Devi',
    age: 26,
    gender: 'Female',
    village: 'Shyampur, Gali 2',
    contact: '+91 94120 77819',
    symptoms: ['High fever 103.8°F (5 days)', 'Severe retro-orbital pain', 'Petechiae spots on forearms', 'Platelet count drop'],
    vitals: {
      bloodPressure: '96/62',
      heartRate: 102,
      spO2: 96,
      temperature: 103.8,
      respiratoryRate: 20,
    },
    severity: 'ESI-2',
    triageReason: 'Probable Dengue Haemorrhagic Fever with warning signs of impending shock. Close hemodynamic monitoring indicated.',
    timestamp: '25 mins ago',
    assignedDoctor: 'Dr. Rajiv Verma',
    status: 'Waiting',
    recommendedActions: [
      'Stat IV Isotonic Fluid Resuscitation (Normal Saline)',
      'Stat NS1 Antigen & IgM/IgG Serology + Complete Blood Count',
      'Continuous blood pressure and urine output hourly charting',
    ],
  },
  {
    id: 'PT-9023',
    name: 'Aarav Sharma',
    age: 6,
    gender: 'Male',
    village: 'Bhimnagar',
    contact: '+91 88712 39012',
    symptoms: ['Acute watery diarrhea x 8 episodes', 'Sunken fontanelle & dry mucous membranes', 'Lethargy'],
    vitals: {
      bloodPressure: '88/54',
      heartRate: 130,
      spO2: 97,
      temperature: 99.1,
      respiratoryRate: 28,
    },
    severity: 'ESI-2',
    triageReason: 'Severe Dehydration secondary to Acute Gastroenteritis. Pediatric fluid resuscitation urgency.',
    timestamp: '40 mins ago',
    assignedDoctor: 'Dr. Anita Deshmukh',
    status: 'In Consultation',
    recommendedActions: [
      'Pediatric IV Ringer Lactate rapid bolus',
      'Oral Rehydration Solution (WHO-ORS) + Zinc sulphate 20mg',
      'Stool culture & rapid cholera dipstick testing',
    ],
  },
  {
    id: 'PT-9024',
    name: 'Kamala Bai',
    age: 64,
    gender: 'Female',
    village: 'Shivajinagar',
    contact: '+91 91230 45890',
    symptoms: ['Productive cough > 3 weeks', 'Evening low grade fever', 'Unexplained weight loss 5kg'],
    vitals: {
      bloodPressure: '124/80',
      heartRate: 78,
      spO2: 95,
      temperature: 100.2,
      respiratoryRate: 18,
    },
    severity: 'ESI-3',
    triageReason: 'NTEP presumptive Pulmonary Tuberculosis. Sputum smear & NAAT (CBNAAT/Truenat) protocol.',
    timestamp: '1 hour ago',
    status: 'Waiting',
    recommendedActions: [
      'Collect 2 Sputum Samples for Truenat MTB/RIF test',
      'Chest X-Ray requisition',
      'Nutritional counseling & Ni-kshay portal registration',
    ],
  },
  {
    id: 'PT-9025',
    name: 'Gopal Krishna',
    age: 42,
    gender: 'Male',
    village: 'Kalyanpur, Outer Fields',
    contact: '+91 97654 22019',
    symptoms: ['Superficial laceration on right index finger from farming sickle', 'Bleeding controlled'],
    vitals: {
      bloodPressure: '120/82',
      heartRate: 72,
      spO2: 99,
      temperature: 98.6,
      respiratoryRate: 14,
    },
    severity: 'ESI-4',
    triageReason: 'Minor trauma. Clean wound management and Tetanus toxoid booster indicated.',
    timestamp: '1 hour ago',
    status: 'Waiting',
    recommendedActions: [
      'Wound irrigation with normal saline & povidone iodine',
      'Tetanus Toxoid 0.5ml IM booster',
      'Steri-strip / single suture dressing',
    ],
  },
];

export const PHC_CENTERS: PHCCenter[] = [
  {
    id: 'PHC-01',
    name: 'Kalyanpur Model Primary Health Centre',
    constituency: 'Varanasi North / East Division',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    coordinates: [25.3176, 82.9739],
    bedsTotal: 24,
    bedsOccupied: 19,
    oxygenCylindersAvailable: 8,
    antivenomVials: 14,
    paracetamolStock: 4200,
    doctorsOnDuty: 3,
    ambulancesAvailable: 2,
    activeOutbreakAlert: 'Dengue Cluster (6 active cases)',
  },
  {
    id: 'PHC-02',
    name: 'Bhimnagar Rural PHC & Maternity Unit',
    constituency: 'Chandauli Rural',
    district: 'Chandauli',
    state: 'Uttar Pradesh',
    coordinates: [25.2612, 83.2707],
    bedsTotal: 16,
    bedsOccupied: 14,
    oxygenCylindersAvailable: 3,
    antivenomVials: 5,
    paracetamolStock: 1800,
    doctorsOnDuty: 2,
    ambulancesAvailable: 1,
    activeOutbreakAlert: 'Pediatric Viral Gastroenteritis',
  },
  {
    id: 'PHC-03',
    name: 'Shyampur Community Health Centre',
    constituency: 'Mirzapur East',
    district: 'Mirzapur',
    state: 'Uttar Pradesh',
    coordinates: [25.1337, 82.5644],
    bedsTotal: 30,
    bedsOccupied: 21,
    oxygenCylindersAvailable: 12,
    antivenomVials: 22,
    paracetamolStock: 6500,
    doctorsOnDuty: 4,
    ambulancesAvailable: 3,
  },
  {
    id: 'PHC-04',
    name: 'Shivajinagar Tribal Sub-Centre',
    constituency: 'Sonbhadra Highland',
    district: 'Sonbhadra',
    state: 'Uttar Pradesh',
    coordinates: [24.6850, 83.0680],
    bedsTotal: 10,
    bedsOccupied: 8,
    oxygenCylindersAvailable: 2,
    antivenomVials: 3, // LOW WARNING
    paracetamolStock: 900,
    doctorsOnDuty: 1,
    ambulancesAvailable: 1,
    activeOutbreakAlert: 'Malaria Vivax Surge',
  },
];

export const ACTIVE_OUTBREAKS: DiseaseOutbreak[] = [
  {
    id: 'OB-101',
    diseaseName: 'Dengue Fever (Serotype 2)',
    casesReported: 47,
    riskLevel: 'High',
    trend: 'Rising',
    hotspotVillage: 'Kalyanpur Lowlands & Drainage Canal',
    coordinates: [25.3210, 82.9810],
    recommendedProtocol: 'Initiate municipal larvicidal fogging (Abate 1%), door-to-door ASHA fever surveys, and platelet contingency stocking.',
    affectedPopulationEstimate: 14500,
  },
  {
    id: 'OB-102',
    diseaseName: 'Acute Diarrheal Disease (Cholera risk)',
    casesReported: 29,
    riskLevel: 'High',
    trend: 'Rising',
    hotspotVillage: 'Bhimnagar Well No. 3 Catchment',
    coordinates: [25.2650, 83.2750],
    recommendedProtocol: 'Super-chlorination of community wells to 2ppm, distribution of 5,000 ORS-Zinc kits, and tap water boil advisory.',
    affectedPopulationEstimate: 8200,
  },
  {
    id: 'OB-103',
    diseaseName: 'Plasmodium Vivax Malaria',
    casesReported: 18,
    riskLevel: 'Moderate',
    trend: 'Stable',
    hotspotVillage: 'Sonbhadra Forest Fringe',
    coordinates: [24.6900, 83.0720],
    recommendedProtocol: 'Indoor Residual Spraying (IRS) with synthetic pyrethroids and distributed Long-Lasting Insecticidal Nets (LLINs).',
    affectedPopulationEstimate: 5400,
  },
];

export const SAMPLE_PRESCRIPTION_RESULT: PrescriptionAnalysisResult = {
  patientName: 'Rameshwar Patil (Age 58)',
  diagnosedCondition: 'Acute Coronary Syndrome / Post-Angioplasty Regimen & Hypertension',
  confidenceScore: 97.4,
  medications: [
    {
      name: 'Tab. Ecosprin AV 75/20',
      dosage: '75mg Aspirin + 20mg Atorvastatin',
      frequency: 'Once Daily (1-0-0)',
      duration: '90 Days',
      instructions: 'Take strictly after dinner with a full glass of water. Do not skip.',
      vernacularExplanation: 'खून पतला करने और कोलेस्ट्रॉल कम करने की दवा। रात के खाने के बाद लें। (Blood thinner and cholesterol medication).',
    },
    {
      name: 'Tab. Telmisartan 40mg',
      dosage: '40mg',
      frequency: 'Once Daily (1-0-0)',
      duration: 'Continuous',
      instructions: 'Take early morning before breakfast. Monitor BP weekly.',
      vernacularExplanation: 'ब्लड प्रेशर (BP) नियंत्रित रखने की गोली। सुबह खाली पेट या नाश्ते के बाद लें।',
    },
    {
      name: 'Tab. Metoprolol Succinate ER 25mg',
      dosage: '25mg',
      frequency: 'Once Daily (0-1-0)',
      duration: '60 Days',
      instructions: 'Take at 2 PM. Slows down heart strain.',
      vernacularExplanation: 'दिल की धड़कन को सामान्य और शांत रखने के लिए दवा।',
    },
    {
      name: 'Tab. Pantoprazole 40mg',
      dosage: '40mg',
      frequency: 'Once Daily (1-0-0)',
      duration: '30 Days',
      instructions: 'Take 30 minutes before morning tea/breakfast.',
      vernacularExplanation: 'पेट में गैस और जलन से बचाव की गोली। सुबह खाली पेट लें।',
    },
  ],
  criticalWarnings: [
    '⚠️ NEVER stop Ecosprin suddenly without cardiologist consultation — risk of stent thrombosis.',
    '⚠️ Avoid NSAID pain relievers (like Ibuprofen/Diclofenac) as they increase bleeding risk.',
  ],
  dietaryAdvice: [
    'Strict low-sodium diet (< 3 grams salt per day / half teaspoon).',
    'Avoid fried foods, coconut oil, and red meat.',
    'Include garlic, steamed leafy greens, and oats in breakfast.',
  ],
  followUpDays: 14,
  emergencySigns: [
    'Recurrent chest tightness or heavy sweating',
    'Shortness of breath while lying flat',
    'Black-colored stools (gastrointestinal bleeding sign)',
  ],
  extractedRawText: `Rx:
1. Tab. Ecosprin-AV (75/20) - 1 tab PO OD (Post dinner) x 3 months
2. Tab. Telma 40 mg - 1 tab PO OD (Morning) x Continuous
3. Tab. Betaloc 25 mg ER - 1 tab PO OD (Post Lunch) x 2 months
4. Tab. Pantocid 40 mg - 1 tab PO OD (Empty stomach) x 1 month
Advice: Low salt, lipid profile after 4 weeks. Review in PHC / OPD in 14 days.`,
};
